# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2_kayttoliittyma.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(991, 558)
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(360, 310, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.nimiKentta = QtWidgets.QLineEdit(Form)
        self.nimiKentta.setGeometry(QtCore.QRect(280, 220, 171, 41))
        self.nimiKentta.setObjectName("nimiKentta")
        self.summaKentta = QtWidgets.QLineEdit(Form)
        self.summaKentta.setGeometry(QtCore.QRect(540, 220, 171, 41))
        self.summaKentta.setObjectName("summaKentta")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(330, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(570, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.naytaButton = QtWidgets.QPushButton(Form)
        self.naytaButton.setGeometry(QtCore.QRect(360, 400, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.naytaButton.setFont(font)
        self.naytaButton.setObjectName("naytaButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button.setText(_translate("Form", "TALLENNA TIEDOT"))
        self.label.setText(_translate("Form", "Nimi"))
        self.label_2.setText(_translate("Form", "Summa"))
        self.naytaButton.setText(_translate("Form", "NÄYTÄ TIEDOT"))
